var data = [
  {
    "name": "Albania",
    "exports": [
      "Argentina",
      "Australia",
      "Austria",
      "Bangladesh",
      "Armenia",
      "Belgium",
      "Bosnia and Herzegovina",
      "Brazil",
      "Bulgaria",
      "Canada",
      "China",
      "Chinese Taipei",
      "Congo",
      "Croatia",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "Ecuador",
      "Estonia",
      "France",
      "Germany",
      "Greece",
      "Hong Kong, China",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran",
      "Ireland",
      "Italy",
      "Japan",
      "Jordan",
      "Korea, Republic of",
      "Latvia",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Mexico",
      "Netherlands",
      "New Zealand",
      "Norway",
      "Pakistan",
      "Peru",
      "Poland",
      "Portugal",
      "Romania",
      "Russian Federation",
      "Singapore",
      "Slovak Republic",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "Eswatini",
      "Sweden",
      "Switzerland",
      "Thailand",
      "Turkey",
      "Ukraine",
      "North Macedonia",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Uruguay",
      "Serbia"
    ]
  },
  {
    "name": "Argentina",
    "exports": [
      "Australia",
      "Austria",
      "Belgium",
      "Brazil",
      "Bulgaria",
      "Canada",
      "Chile",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Costa Rica",
      "Cuba",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "El Salvador",
      "Finland",
      "France",
      "Germany",
      "Greece",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Ireland",
      "Israel",
      "Italy",
      "Japan",
      "Korea, Republic of",
      "Latvia",
      "Liechtenstein",
      "Lithuania",
      "Malaysia",
      "Mexico",
      "Nepal",
      "Netherlands",
      "New Zealand",
      "Norway",
      "Pakistan",
      "Paraguay",
      "Peru",
      "Poland",
      "Portugal",
      "Romania",
      "Russian Federation",
      "Singapore",
      "Slovak Republic",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "Sweden",
      "Switzerland",
      "Thailand",
      "United Arab Emirates",
      "Turkey",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Uruguay",
      "Venezuela, Bolivarian Republic of"
    ]
  },
  {
    "name": "Australia",
    "exports": [
      "Argentina",
      "Austria",
      "Bangladesh",
      "Belgium",
      "Bosnia and Herzegovina",
      "Brazil",
      "Bulgaria",
      "Belarus",
      "Cambodia",
      "Canada",
      "Sri Lanka",
      "Chile",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Costa Rica",
      "Croatia",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "Estonia",
      "Fiji",
      "Finland",
      "France",
      "Gabon",
      "Georgia",
      "Germany",
      "Greece",
      "Hong Kong, China",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran",
      "Ireland",
      "Israel",
      "Italy",
      "Jamaica",
      "Japan",
      "Kenya",
      "Korea, Republic of",
      "Latvia",
      "Lithuania",
      "Luxembourg",
      "Macao, China",
      "Malaysia",
      "Mali",
      "Malta",
      "Mauritius",
      "Mexico",
      "Morocco",
      "Oman",
      "Nepal",
      "Netherlands",
      "New Zealand",
      "Niger",
      "Norway",
      "Pakistan",
      "Papua New Guinea",
      "Philippines",
      "Poland",
      "Portugal",
      "Romania",
      "Russian Federation",
      "Saudi Arabia, Kingdom of",
      "Sierra Leone",
      "Singapore",
      "Slovak Republic",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "Sweden",
      "Switzerland",
      "Thailand",
      "United Arab Emirates",
      "Turkey",
      "Uganda",
      "Ukraine",
      "North Macedonia",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Venezuela, Bolivarian Republic of",
      "Samoa",
      "Serbia"
    ]
  },
  {
    "name": "Bolivia, Plurinational State of",
    "exports": [
      "Argentina",
      "Australia",
      "Austria",
      "Bangladesh",
      "Belgium",
      "Brazil",
      "Bulgaria",
      "Canada",
      "Chile",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Costa Rica",
      "Cuba",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "Ecuador",
      "El Salvador",
      "Finland",
      "France",
      "Germany",
      "Greece",
      "Guatemala",
      "Honduras",
      "Hong Kong, China",
      "Hungary",
      "India",
      "Ireland",
      "Israel",
      "Italy",
      "Japan",
      "Jordan",
      "Korea, Republic of",
      "Latvia",
      "Malaysia",
      "Mexico",
      "Netherlands",
      "Norway",
      "Panama",
      "Paraguay",
      "Peru",
      "Poland",
      "Portugal",
      "Russian Federation",
      "Slovenia",
      "Spain",
      "Sweden",
      "Switzerland",
      "Thailand",
      "Turkey",
      "Ukraine",
      "United Kingdom",
      "United States of America",
      "Uruguay"
    ]
  },
  {
    "name": "Brazil",
    "exports": [
      "Argentina",
      "Australia",
      "Austria",
      "Bangladesh",
      "Belgium",
      "Bulgaria",
      "Belarus",
      "Cambodia",
      "Canada",
      "Chile",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Costa Rica",
      "Cuba",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "Ecuador",
      "Estonia",
      "Finland",
      "France",
      "Germany",
      "Greece",
      "Hong Kong, China",
      "Hungary",
      "India",
      "Indonesia",
      "Iran",
      "Ireland",
      "Israel",
      "Italy",
      "Japan",
      "Jordan",
      "Korea, Republic of",
      "Latvia",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Malaysia",
      "Malta",
      "Mexico",
      "Morocco",
      "Nepal",
      "Netherlands",
      "New Zealand",
      "Norway",
      "Paraguay",
      "Peru",
      "Poland",
      "Portugal",
      "Romania",
      "Russian Federation",
      "Singapore",
      "Slovak Republic",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "Sweden",
      "Switzerland",
      "Thailand",
      "Turkey",
      "Ukraine",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Uruguay",
      "Venezuela, Bolivarian Republic of"
    ]
  },
  {
    "name": "Belize",
    "exports": [
      "Argentina",
      "Australia",
      "Bangladesh",
      "Barbados",
      "Belgium",
      "Bolivia, Plurinational State of",
      "Brazil",
      "Canada",
      "Chile",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Costa Rica",
      "Cuba",
      "Denmark",
      "El Salvador",
      "Finland",
      "France",
      "Germany",
      "Greece",
      "Guatemala",
      "Honduras",
      "Hong Kong, China",
      "India",
      "Israel",
      "Italy",
      "Jamaica",
      "Japan",
      "Korea, Republic of",
      "Mexico",
      "Netherlands",
      "New Zealand",
      "Nicaragua",
      "Pakistan",
      "Panama",
      "Paraguay",
      "Singapore",
      "Zimbabwe",
      "Spain",
      "Switzerland",
      "Trinidad and Tobago",
      "Turkey",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Uruguay"
    ]
  },
  {
    "name": "Brunei Darussalam",
    "exports": [
      "Australia",
      "Austria",
      "Bangladesh",
      "Belgium",
      "Canada",
      "China",
      "Chinese Taipei",
      "Denmark",
      "Dominica",
      "Finland",
      "France",
      "Georgia",
      "Germany",
      "Greece",
      "Hong Kong, China",
      "Hungary",
      "India",
      "Indonesia",
      "Ireland",
      "Italy",
      "Japan",
      "Korea, Republic of",
      "Malawi",
      "Malaysia",
      "Maldives",
      "Mexico",
      "Netherlands",
      "New Zealand",
      "Niger",
      "Norway",
      "Philippines",
      "Poland",
      "Russian Federation",
      "Singapore",
      "Slovak Republic",
      "Viet Nam",
      "Spain",
      "Sweden",
      "Switzerland",
      "Thailand",
      "United Arab Emirates",
      "Turkey",
      "Egypt",
      "United Kingdom",
      "United States of America"
    ]
  },
  {
    "name": "Myanmar",
    "exports": [
      "Argentina",
      "Australia",
      "Austria",
      "Bangladesh",
      "Belgium",
      "Brazil",
      "Bulgaria",
      "Canada",
      "Sri Lanka",
      "Chile",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Cuba",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Ecuador",
      "Ethiopia",
      "Finland",
      "France",
      "Gabon",
      "Germany",
      "Greece",
      "Guatemala",
      "Hong Kong, China",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran",
      "Ireland",
      "Israel",
      "Italy",
      "Japan",
      "Kenya",
      "Korea, Republic of",
      "Lao People's Democratic Republic",
      "Liechtenstein",
      "Macao, China",
      "Malaysia",
      "Malta",
      "Mexico",
      "Moldova, Republic of",
      "Oman",
      "Nepal",
      "Netherlands",
      "New Zealand",
      "Pakistan",
      "Papua New Guinea",
      "Paraguay",
      "Philippines",
      "Poland",
      "Portugal",
      "Romania",
      "Russian Federation",
      "Saint Kitts and Nevis",
      "Singapore",
      "Slovak Republic",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "Eswatini",
      "Sweden",
      "Switzerland",
      "Thailand",
      "United Arab Emirates",
      "Tunisia",
      "Turkey",
      "Ukraine",
      "Egypt",
      "United Kingdom",
      "United States of America"
    ]
  },
  {
    "name": "Canada",
    "exports": [
      "Afghanistan",
      "Albania",
      "Algeria",
      "Andorra",
      "Angola",
      "Antigua and Barbuda",
      "Azerbaijan",
      "Argentina",
      "Australia",
      "Austria",
      "Bahamas",
      "Bahrain, Kingdom of",
      "Bangladesh",
      "Armenia",
      "Barbados",
      "Belgium",
      "Bhutan",
      "Bolivia, Plurinational State of",
      "Bosnia and Herzegovina",
      "Botswana",
      "Brazil",
      "Belize",
      "Bulgaria",
      "Myanmar",
      "Burundi",
      "Cambodia",
      "Cameroon",
      "Sri Lanka",
      "Chile",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Congo",
      "Democratic Republic of the Congo",
      "Costa Rica",
      "Croatia",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Dominica",
      "Dominican Republic",
      "Ecuador",
      "El Salvador",
      "Ethiopia",
      "Estonia",
      "Fiji",
      "Finland",
      "France",
      "Djibouti",
      "Georgia",
      "Germany",
      "Ghana",
      "Greece",
      "Grenada",
      "Guatemala",
      "Guinea",
      "Guyana",
      "Haiti",
      "Honduras",
      "Hong Kong, China",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran",
      "Ireland",
      "Israel",
      "Italy",
      "Cote d'Ivoire",
      "Jamaica",
      "Japan",
      "Jordan",
      "Kenya",
      "Korea, Republic of",
      "Kuwait, the State of",
      "Lebanese Republic",
      "Lesotho",
      "Latvia",
      "Liberia",
      "Libya",
      "Lithuania",
      "Luxembourg",
      "Macao, China",
      "Madagascar",
      "Malawi",
      "Malaysia",
      "Mali",
      "Malta",
      "Mauritania",
      "Mauritius",
      "Mexico",
      "Mongolia",
      "Moldova, Republic of",
      "Morocco",
      "Oman",
      "Namibia",
      "Nepal",
      "Netherlands",
      "New Zealand",
      "Nicaragua",
      "Niger",
      "Nigeria",
      "Norway",
      "Pakistan",
      "Panama",
      "Paraguay",
      "Peru",
      "Philippines",
      "Poland",
      "Portugal",
      "Qatar",
      "Romania",
      "Russian Federation",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Saint Vincent and the Grenadines",
      "Saudi Arabia, Kingdom of",
      "Senegal",
      "Seychelles",
      "Sierra Leone",
      "Singapore",
      "Slovak Republic",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Zimbabwe",
      "Spain",
      "Sudan",
      "Suriname",
      "Eswatini",
      "Sweden",
      "Switzerland",
      "Thailand",
      "Togo",
      "Trinidad and Tobago",
      "United Arab Emirates",
      "Tunisia",
      "Turkey",
      "Uganda",
      "Ukraine",
      "North Macedonia",
      "Egypt",
      "United Kingdom",
      "Tanzania",
      "United States of America",
      "Burkina Faso",
      "Uruguay",
      "Venezuela, Bolivarian Republic of",
      "Yemen",
      "Serbia",
      "Zambia"
    ]
  },
  {
    "name": "China",
    "exports": [
      "Argentina",
      "Australia",
      "Austria",
      "Bangladesh",
      "Barbados",
      "Belgium",
      "Brazil",
      "Bulgaria",
      "Cambodia",
      "Canada",
      "Sri Lanka",
      "Chinese Taipei",
      "Colombia",
      "Costa Rica",
      "Croatia",
      "Cuba",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "Estonia",
      "Finland",
      "France",
      "Germany",
      "Greece",
      "Hong Kong, China",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran",
      "Ireland",
      "Israel",
      "Italy",
      "Japan",
      "Jordan",
      "Kenya",
      "Korea, Republic of",
      "Latvia",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Macao, China",
      "Malaysia",
      "Malta",
      "Mexico",
      "Nepal",
      "Netherlands",
      "New Zealand",
      "Nicaragua",
      "Nigeria",
      "Norway",
      "Pakistan",
      "Peru",
      "Philippines",
      "Poland",
      "Portugal",
      "Romania",
      "Russian Federation",
      "Saudi Arabia, Kingdom of",
      "Singapore",
      "Slovak Republic",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "Sweden",
      "Switzerland",
      "Thailand",
      "Trinidad and Tobago",
      "United Arab Emirates",
      "Tunisia",
      "Turkey",
      "Ukraine",
      "North Macedonia",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Uruguay",
      "Serbia"
    ]
  },
  {
    "name": "Chinese Taipei",
    "exports": [
      "Argentina",
      "Australia",
      "Austria",
      "Bangladesh",
      "Barbados",
      "Belgium",
      "Brazil",
      "Bulgaria",
      "Cambodia",
      "Canada",
      "China",
      "Colombia",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "Estonia",
      "Finland",
      "France",
      "Germany",
      "Greece",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Ireland",
      "Israel",
      "Italy",
      "Japan",
      "Jordan",
      "Korea, Republic of",
      "Liechtenstein",
      "Lithuania",
      "Malaysia",
      "Malta",
      "Mexico",
      "Nepal",
      "Netherlands",
      "New Zealand",
      "Norway",
      "Philippines",
      "Poland",
      "Portugal",
      "Romania",
      "Russian Federation",
      "Singapore",
      "Slovak Republic",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "Sweden",
      "Switzerland",
      "Thailand",
      "United Arab Emirates",
      "Turkey",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Venezuela, Bolivarian Republic of"
    ]
  },
  {
    "name": "Colombia",
    "exports": [
      "Argentina",
      "Australia",
      "Austria",
      "Bangladesh",
      "Belgium",
      "Brazil",
      "Bulgaria",
      "Cameroon",
      "Canada",
      "Chile",
      "China",
      "Chinese Taipei",
      "Costa Rica",
      "Croatia",
      "Cuba",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "Ecuador",
      "El Salvador",
      "Finland",
      "France",
      "Georgia",
      "Germany",
      "Greece",
      "Guatemala",
      "Hong Kong, China",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran",
      "Ireland",
      "Israel",
      "Italy",
      "Cote d'Ivoire",
      "Japan",
      "Korea, Republic of",
      "Latvia",
      "Liechtenstein",
      "Lithuania",
      "Malaysia",
      "Malta",
      "Mexico",
      "Oman",
      "Netherlands",
      "New Zealand",
      "Norway",
      "Panama",
      "Paraguay",
      "Peru",
      "Philippines",
      "Poland",
      "Portugal",
      "Romania",
      "Russian Federation",
      "Singapore",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "Sweden",
      "Switzerland",
      "Thailand",
      "Turkey",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Uruguay",
      "Venezuela, Bolivarian Republic of"
    ]
  },
  {
    "name": "Costa Rica",
    "exports": [
      "Argentina",
      "Australia",
      "Austria",
      "Bahamas",
      "Bahrain, Kingdom of",
      "Bangladesh",
      "Barbados",
      "Belgium",
      "Bolivia, Plurinational State of",
      "Botswana",
      "Brazil",
      "Belize",
      "Bulgaria",
      "Canada",
      "Chile",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Comoros",
      "Croatia",
      "Cuba",
      "Czech Republic",
      "Denmark",
      "Dominica",
      "Dominican Republic",
      "Ecuador",
      "El Salvador",
      "Finland",
      "France",
      "Germany",
      "Greece",
      "Guatemala",
      "Haiti",
      "Honduras",
      "Hong Kong, China",
      "Hungary",
      "Iceland",
      "India",
      "Ireland",
      "Israel",
      "Italy",
      "Jamaica",
      "Japan",
      "Kenya",
      "Korea, Republic of",
      "Latvia",
      "Liechtenstein",
      "Lithuania",
      "Malaysia",
      "Malta",
      "Mauritius",
      "Mexico",
      "Netherlands",
      "New Zealand",
      "Nicaragua",
      "Norway",
      "Pakistan",
      "Panama",
      "Paraguay",
      "Peru",
      "Philippines",
      "Poland",
      "Portugal",
      "Romania",
      "Singapore",
      "Slovenia",
      "South Africa",
      "Spain",
      "Sweden",
      "Switzerland",
      "Thailand",
      "Trinidad and Tobago",
      "United Arab Emirates",
      "Turkey",
      "Ukraine",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Uruguay",
      "Venezuela, Bolivarian Republic of"
    ]
  },
  {
    "name": "Cuba",
    "exports": [
      "Argentina",
      "Australia",
      "Austria",
      "Belgium",
      "Brazil",
      "Belarus",
      "Canada",
      "Chile",
      "China",
      "Colombia",
      "Costa Rica",
      "Denmark",
      "Dominican Republic",
      "El Salvador",
      "France",
      "Germany",
      "Greece",
      "Guatemala",
      "Hungary",
      "India",
      "Ireland",
      "Italy",
      "Japan",
      "Korea, Republic of",
      "Liechtenstein",
      "Mexico",
      "Netherlands",
      "New Zealand",
      "Pakistan",
      "Panama",
      "Paraguay",
      "Poland",
      "Portugal",
      "Romania",
      "Russian Federation",
      "Viet Nam",
      "Spain",
      "Sweden",
      "Switzerland",
      "Turkey",
      "Ukraine",
      "United Kingdom",
      "United States of America",
      "Uruguay"
    ]
  },
  {
    "name": "Ecuador",
    "exports": [
      "Afghanistan",
      "Argentina",
      "Australia",
      "Austria",
      "Bangladesh",
      "Belgium",
      "Brazil",
      "Bulgaria",
      "Canada",
      "Chile",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Costa Rica",
      "Cuba",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "El Salvador",
      "Finland",
      "France",
      "Georgia",
      "Germany",
      "Guatemala",
      "Hong Kong, China",
      "Hungary",
      "India",
      "Indonesia",
      "Iran",
      "Ireland",
      "Israel",
      "Italy",
      "Japan",
      "Jordan",
      "Korea, Republic of",
      "Liechtenstein",
      "Malaysia",
      "Mexico",
      "Netherlands",
      "New Zealand",
      "Norway",
      "Pakistan",
      "Panama",
      "Paraguay",
      "Peru",
      "Poland",
      "Portugal",
      "Romania",
      "Russian Federation",
      "Singapore",
      "Slovenia",
      "South Africa",
      "Spain",
      "Suriname",
      "Sweden",
      "Switzerland",
      "Thailand",
      "United Arab Emirates",
      "Turkey",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Uruguay",
      "Venezuela, Bolivarian Republic of"
    ]
  },
  {
    "name": "El Salvador",
    "exports": [
      "Antigua and Barbuda",
      "Argentina",
      "Australia",
      "Austria",
      "Bangladesh",
      "Belgium",
      "Brazil",
      "Bulgaria",
      "Canada",
      "Chile",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Costa Rica",
      "Croatia",
      "Cuba",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "Ecuador",
      "Finland",
      "France",
      "Germany",
      "Greece",
      "Guatemala",
      "Honduras",
      "Hong Kong, China",
      "Hungary",
      "India",
      "Indonesia",
      "Ireland",
      "Israel",
      "Italy",
      "Japan",
      "Korea, Republic of",
      "Malaysia",
      "Mexico",
      "Netherlands",
      "New Zealand",
      "Nicaragua",
      "Norway",
      "Panama",
      "Paraguay",
      "Peru",
      "Philippines",
      "Poland",
      "Portugal",
      "Romania",
      "Russian Federation",
      "Singapore",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "Suriname",
      "Eswatini",
      "Sweden",
      "Switzerland",
      "Thailand",
      "Turkey",
      "Ukraine",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Uruguay",
      "Venezuela, Bolivarian Republic of"
    ]
  },
  {
    "name": "Georgia",
    "exports": [
      "Azerbaijan",
      "Argentina",
      "Australia",
      "Austria",
      "Bangladesh",
      "Armenia",
      "Belgium",
      "Bosnia and Herzegovina",
      "Brazil",
      "Bulgaria",
      "Belarus",
      "Cambodia",
      "Canada",
      "China",
      "Colombia",
      "Croatia",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Estonia",
      "Finland",
      "France",
      "Germany",
      "Greece",
      "Hong Kong, China",
      "Hungary",
      "India",
      "Iran",
      "Ireland",
      "Israel",
      "Italy",
      "Japan",
      "Kazakhstan",
      "Korea, Republic of",
      "Lebanese Republic",
      "Latvia",
      "Lithuania",
      "Luxembourg",
      "Malaysia",
      "Malta",
      "Mexico",
      "Moldova, Republic of",
      "Netherlands",
      "New Zealand",
      "Norway",
      "Pakistan",
      "Poland",
      "Portugal",
      "Romania",
      "Russian Federation",
      "Singapore",
      "Slovak Republic",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "Switzerland",
      "Tajikistan",
      "Thailand",
      "United Arab Emirates",
      "Turkey",
      "Ukraine",
      "North Macedonia",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Uruguay",
      "Uzbekistan",
      "Serbia"
    ]
  },
  {
    "name": "Hong Kong, China",
    "exports": [
      "Andorra",
      "Argentina",
      "Australia",
      "Austria",
      "Bangladesh",
      "Belgium",
      "Brazil",
      "Bulgaria",
      "Belarus",
      "Cambodia",
      "Canada",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Croatia",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "Ecuador",
      "Finland",
      "France",
      "Germany",
      "Greece",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Ireland",
      "Israel",
      "Italy",
      "Japan",
      "Jordan",
      "Korea, Republic of",
      "Lesotho",
      "Liechtenstein",
      "Luxembourg",
      "Macao, China",
      "Malaysia",
      "Malta",
      "Mexico",
      "Morocco",
      "Namibia",
      "Netherlands",
      "New Zealand",
      "Norway",
      "Pakistan",
      "Panama",
      "Philippines",
      "Poland",
      "Portugal",
      "Romania",
      "Saudi Arabia, Kingdom of",
      "Singapore",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "South Sudan",
      "Eswatini",
      "Sweden",
      "Switzerland",
      "Thailand",
      "Tunisia",
      "Turkey",
      "Ukraine",
      "North Macedonia",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Uruguay",
      "Serbia"
    ]
  },
  {
    "name": "Indonesia",
    "exports": [
      "Andorra",
      "Argentina",
      "Australia",
      "Austria",
      "Bangladesh",
      "Belgium",
      "Brazil",
      "Bulgaria",
      "Cambodia",
      "Canada",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Croatia",
      "Cuba",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "Ecuador",
      "Finland",
      "France",
      "Germany",
      "Greece",
      "Hong Kong, China",
      "Hungary",
      "Iceland",
      "India",
      "Iran",
      "Ireland",
      "Israel",
      "Italy",
      "Japan",
      "Jordan",
      "Korea, Republic of",
      "Latvia",
      "Lithuania",
      "Luxembourg",
      "Macao, China",
      "Malaysia",
      "Malta",
      "Mauritius",
      "Mexico",
      "Netherlands",
      "New Zealand",
      "Norway",
      "Pakistan",
      "Peru",
      "Philippines",
      "Poland",
      "Portugal",
      "Romania",
      "Russian Federation",
      "Singapore",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "Sweden",
      "Switzerland",
      "Thailand",
      "United Arab Emirates",
      "Turkey",
      "Ukraine",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Venezuela, Bolivarian Republic of"
    ]
  },
  {
    "name": "Israel",
    "exports": [
      "Afghanistan",
      "Argentina",
      "Australia",
      "Austria",
      "Belgium",
      "Brazil",
      "Bulgaria",
      "Canada",
      "Chile",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Croatia",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Dominica",
      "Dominican Republic",
      "El Salvador",
      "Estonia",
      "Finland",
      "France",
      "Georgia",
      "Germany",
      "Ghana",
      "Greece",
      "Hong Kong, China",
      "Hungary",
      "Iceland",
      "India",
      "Ireland",
      "Italy",
      "Japan",
      "Jordan",
      "Korea, Republic of",
      "Latvia",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Malta",
      "Mexico",
      "Netherlands",
      "New Zealand",
      "Norway",
      "Pakistan",
      "Panama",
      "Philippines",
      "Poland",
      "Portugal",
      "Romania",
      "Russian Federation",
      "Singapore",
      "Slovak Republic",
      "Slovenia",
      "South Africa",
      "Spain",
      "Sweden",
      "Switzerland",
      "Thailand",
      "Turkey",
      "Ukraine",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Uruguay",
      "Serbia"
    ]
  },
  {
    "name": "Japan",
    "exports": [
      "Argentina",
      "Australia",
      "Austria",
      "Armenia",
      "Belgium",
      "Brazil",
      "Bulgaria",
      "Myanmar",
      "Canada",
      "Sri Lanka",
      "Chile",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Costa Rica",
      "Cuba",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "Finland",
      "France",
      "Germany",
      "Greece",
      "Guatemala",
      "Hong Kong, China",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Ireland",
      "Israel",
      "Italy",
      "Korea, Republic of",
      "Lithuania",
      "Malaysia",
      "Malta",
      "Mexico",
      "Nepal",
      "Netherlands",
      "New Zealand",
      "Nicaragua",
      "Norway",
      "Pakistan",
      "Philippines",
      "Poland",
      "Portugal",
      "Romania",
      "Russian Federation",
      "Singapore",
      "Slovak Republic",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "Sweden",
      "Switzerland",
      "Thailand",
      "Togo",
      "Turkey",
      "Ukraine",
      "United Kingdom",
      "United States of America",
      "Venezuela, Bolivarian Republic of"
    ]
  },
  {
    "name": "Kazakhstan",
    "exports": [
      "Azerbaijan",
      "Argentina",
      "Austria",
      "Armenia",
      "Belgium",
      "Bosnia and Herzegovina",
      "Brazil",
      "Bulgaria",
      "Belarus",
      "Canada",
      "Chile",
      "China",
      "Chinese Taipei",
      "Croatia",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "Estonia",
      "Finland",
      "France",
      "Georgia",
      "Germany",
      "Greece",
      "Hong Kong, China",
      "Hungary",
      "India",
      "Indonesia",
      "Ireland",
      "Israel",
      "Italy",
      "Japan",
      "Jordan",
      "Kenya",
      "Korea, Republic of",
      "Kyrgyz Republic",
      "Latvia",
      "Liechtenstein",
      "Lithuania",
      "Malaysia",
      "Malta",
      "Mexico",
      "Moldova, Republic of",
      "Netherlands",
      "Norway",
      "Pakistan",
      "Poland",
      "Portugal",
      "Romania",
      "Russian Federation",
      "Saudi Arabia, Kingdom of",
      "Singapore",
      "Slovak Republic",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "Sweden",
      "Switzerland",
      "Thailand",
      "Turkey",
      "Ukraine",
      "North Macedonia",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Uruguay",
      "Uzbekistan",
      "Serbia"
    ]
  },
  {
    "name": "Jordan",
    "exports": [
      "Algeria",
      "Azerbaijan",
      "Argentina",
      "Australia",
      "Austria",
      "Belgium",
      "Brazil",
      "Bulgaria",
      "Canada",
      "Chile",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Costa Rica",
      "Croatia",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "El Salvador",
      "Finland",
      "France",
      "Georgia",
      "Germany",
      "Greece",
      "Hungary",
      "India",
      "Iran",
      "Ireland",
      "Italy",
      "Japan",
      "Korea, Republic of",
      "Kuwait, the State of",
      "Lebanese Republic",
      "Latvia",
      "Lithuania",
      "Malaysia",
      "Malta",
      "Mexico",
      "Morocco",
      "Oman",
      "Netherlands",
      "New Zealand",
      "Norway",
      "Pakistan",
      "Poland",
      "Portugal",
      "Qatar",
      "Romania",
      "Russian Federation",
      "Saudi Arabia, Kingdom of",
      "Singapore",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "Sweden",
      "Switzerland",
      "Syrian Arab Republic",
      "Thailand",
      "United Arab Emirates",
      "Tunisia",
      "Turkey",
      "Ukraine",
      "North Macedonia",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Uruguay",
      "Serbia"
    ]
  },
  {
    "name": "Korea, Republic of",
    "exports": [
      "Algeria",
      "Argentina",
      "Australia",
      "Austria",
      "Bangladesh",
      "Belgium",
      "Brazil",
      "Bulgaria",
      "Belarus",
      "Cambodia",
      "Cameroon",
      "Canada",
      "Sri Lanka",
      "Chile",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Costa Rica",
      "Croatia",
      "Cuba",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "Finland",
      "France",
      "Gabon",
      "Georgia",
      "Germany",
      "Ghana",
      "Greece",
      "Guatemala",
      "Guinea",
      "Honduras",
      "Hong Kong, China",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran",
      "Ireland",
      "Israel",
      "Italy",
      "Cote d'Ivoire",
      "Japan",
      "Kazakhstan",
      "Jordan",
      "Kenya",
      "Kuwait, the State of",
      "Lao People's Democratic Republic",
      "Latvia",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Macao, China",
      "Malaysia",
      "Mali",
      "Malta",
      "Mexico",
      "Mongolia",
      "Oman",
      "Nepal",
      "Netherlands",
      "New Zealand",
      "Nigeria",
      "Norway",
      "Pakistan",
      "Panama",
      "Paraguay",
      "Peru",
      "Philippines",
      "Poland",
      "Portugal",
      "Timor-Leste",
      "Romania",
      "Russian Federation",
      "Saudi Arabia, Kingdom of",
      "Sierra Leone",
      "Singapore",
      "Slovak Republic",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "South Sudan",
      "Sudan",
      "Eswatini",
      "Sweden",
      "Switzerland",
      "Syrian Arab Republic",
      "Thailand",
      "United Arab Emirates",
      "Tunisia",
      "Turkey",
      "Uganda",
      "Ukraine",
      "Egypt",
      "United Kingdom",
      "Tanzania",
      "United States of America",
      "Burkina Faso",
      "Uruguay",
      "Venezuela, Bolivarian Republic of",
      "Serbia"
    ]
  },
  {
    "name": "Lao People's Democratic Republic",
    "exports": [
      "Australia",
      "Bangladesh",
      "Belgium",
      "Canada",
      "China",
      "Denmark",
      "Germany",
      "Hong Kong, China",
      "India",
      "Korea, Republic of",
      "Luxembourg",
      "Malaysia",
      "Netherlands",
      "Pakistan",
      "Philippines",
      "Poland",
      "Singapore",
      "Viet Nam",
      "Switzerland",
      "Thailand",
      "United Kingdom"
    ]
  },
  {
    "name": "Macao, China",
    "exports": [
      "Argentina",
      "Australia",
      "Austria",
      "Bangladesh",
      "Belgium",
      "Bolivia, Plurinational State of",
      "Brazil",
      "Bulgaria",
      "Myanmar",
      "Cambodia",
      "Canada",
      "China",
      "Chinese Taipei",
      "Croatia",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "Ecuador",
      "Finland",
      "France",
      "Germany",
      "Greece",
      "Hong Kong, China",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Ireland",
      "Israel",
      "Italy",
      "Japan",
      "Jordan",
      "Korea, Republic of",
      "Malaysia",
      "Malta",
      "Mexico",
      "Netherlands",
      "New Zealand",
      "Norway",
      "Pakistan",
      "Panama",
      "Philippines",
      "Poland",
      "Portugal",
      "Romania",
      "Singapore",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "Sweden",
      "Switzerland",
      "Thailand",
      "Turkey",
      "Egypt",
      "United Kingdom",
      "United States of America"
    ]
  },
  {
    "name": "Madagascar",
    "exports": [
      "Australia",
      "Austria",
      "Bangladesh",
      "Belgium",
      "Brazil",
      "Cameroon",
      "Canada",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "France",
      "Germany",
      "Greece",
      "Hungary",
      "India",
      "Indonesia",
      "Iran",
      "Ireland",
      "Israel",
      "Italy",
      "Cote d'Ivoire",
      "Japan",
      "Kenya",
      "Korea, Republic of",
      "Lithuania",
      "Malaysia",
      "Mauritius",
      "Mexico",
      "Morocco",
      "Netherlands",
      "New Zealand",
      "Norway",
      "Pakistan",
      "Poland",
      "Portugal",
      "Romania",
      "Senegal",
      "Seychelles",
      "Singapore",
      "Slovenia",
      "South Africa",
      "Spain",
      "Sweden",
      "Switzerland",
      "Thailand",
      "United Arab Emirates",
      "Tunisia",
      "Turkey",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Uruguay"
    ]
  },
  {
    "name": "Malaysia",
    "exports": [
      "Argentina",
      "Australia",
      "Austria",
      "Bangladesh",
      "Belgium",
      "Brazil",
      "Brunei Darussalam",
      "Bulgaria",
      "Canada",
      "Sri Lanka",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Costa Rica",
      "Croatia",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Ecuador",
      "Finland",
      "France",
      "Germany",
      "Greece",
      "Hong Kong, China",
      "Hungary",
      "India",
      "Indonesia",
      "Iran",
      "Ireland",
      "Italy",
      "Japan",
      "Jordan",
      "Korea, Republic of",
      "Macao, China",
      "Malta",
      "Mexico",
      "Netherlands",
      "New Zealand",
      "Norway",
      "Pakistan",
      "Peru",
      "Philippines",
      "Poland",
      "Portugal",
      "Romania",
      "Russian Federation",
      "Saudi Arabia, Kingdom of",
      "Singapore",
      "Slovak Republic",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "Sweden",
      "Switzerland",
      "Thailand",
      "United Arab Emirates",
      "Turkey",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Venezuela, Bolivarian Republic of"
    ]
  },
  {
    "name": "Maldives",
    "exports": [
      "Argentina",
      "Australia",
      "Austria",
      "Bangladesh",
      "Belgium",
      "Brazil",
      "Canada",
      "Sri Lanka",
      "China",
      "Chinese Taipei",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Dominica",
      "Ecuador",
      "France",
      "Germany",
      "Hungary",
      "India",
      "Indonesia",
      "Iran",
      "Ireland",
      "Italy",
      "Japan",
      "Korea, Republic of",
      "Malaysia",
      "Mexico",
      "Namibia",
      "Netherlands",
      "New Zealand",
      "Pakistan",
      "Philippines",
      "Poland",
      "Portugal",
      "Russian Federation",
      "Saudi Arabia, Kingdom of",
      "Singapore",
      "Slovenia",
      "South Africa",
      "Spain",
      "Eswatini",
      "Sweden",
      "Switzerland",
      "Thailand",
      "United Arab Emirates",
      "Turkey",
      "Ukraine",
      "Egypt",
      "United Kingdom",
      "United States of America"
    ]
  },
  {
    "name": "Mauritius",
    "exports": [
      "Argentina",
      "Australia",
      "Austria",
      "Bangladesh",
      "Belgium",
      "Brazil",
      "Bulgaria",
      "Canada",
      "Sri Lanka",
      "China",
      "Chinese Taipei",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "Ecuador",
      "Finland",
      "France",
      "Germany",
      "Greece",
      "Honduras",
      "Hong Kong, China",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Ireland",
      "Israel",
      "Italy",
      "Cote d'Ivoire",
      "Japan",
      "Jordan",
      "Kenya",
      "Korea, Republic of",
      "Latvia",
      "Malaysia",
      "Maldives",
      "Mexico",
      "Morocco",
      "Oman",
      "Netherlands",
      "New Zealand",
      "Norway",
      "Pakistan",
      "Paraguay",
      "Peru",
      "Philippines",
      "Poland",
      "Portugal",
      "Romania",
      "Saudi Arabia, Kingdom of",
      "Senegal",
      "Singapore",
      "Slovak Republic",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Zimbabwe",
      "Spain",
      "Sweden",
      "Switzerland",
      "Thailand",
      "United Arab Emirates",
      "Tunisia",
      "Turkey",
      "Egypt",
      "United Kingdom",
      "United States of America"
    ]
  },
  {
    "name": "Mexico",
    "exports": [
      "Argentina",
      "Australia",
      "Austria",
      "Belgium",
      "Brazil",
      "Bulgaria",
      "Cambodia",
      "Canada",
      "Chile",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Costa Rica",
      "Croatia",
      "Cuba",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Dominica",
      "Dominican Republic",
      "Ecuador",
      "El Salvador",
      "Finland",
      "France",
      "Germany",
      "Greece",
      "Guatemala",
      "Honduras",
      "Hong Kong, China",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Ireland",
      "Israel",
      "Italy",
      "Japan",
      "Korea, Republic of",
      "Latvia",
      "Liechtenstein",
      "Lithuania",
      "Malaysia",
      "Malta",
      "Mauritius",
      "Morocco",
      "Netherlands",
      "New Zealand",
      "Nicaragua",
      "Norway",
      "Pakistan",
      "Panama",
      "Paraguay",
      "Peru",
      "Philippines",
      "Poland",
      "Portugal",
      "Romania",
      "Russian Federation",
      "Singapore",
      "Slovak Republic",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "Sweden",
      "Switzerland",
      "Thailand",
      "Turkey",
      "Ukraine",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Uruguay",
      "Venezuela, Bolivarian Republic of",
      "Serbia"
    ]
  },
  {
    "name": "Mongolia",
    "exports": [
      "Argentina",
      "Australia",
      "Austria",
      "Bangladesh",
      "Belgium",
      "Brazil",
      "Bulgaria",
      "Belarus",
      "Canada",
      "China",
      "Chinese Taipei",
      "Costa Rica",
      "Croatia",
      "Cuba",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "Finland",
      "France",
      "Georgia",
      "Germany",
      "Greece",
      "Hong Kong, China",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Ireland",
      "Israel",
      "Italy",
      "Japan",
      "Kazakhstan",
      "Jordan",
      "Korea, Republic of",
      "Latvia",
      "Luxembourg",
      "Malaysia",
      "Malta",
      "Mexico",
      "Netherlands",
      "New Zealand",
      "Norway",
      "Pakistan",
      "Poland",
      "Portugal",
      "Romania",
      "Russian Federation",
      "Saudi Arabia, Kingdom of",
      "Singapore",
      "Slovak Republic",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "Eswatini",
      "Sweden",
      "Switzerland",
      "Thailand",
      "Turkey",
      "Ukraine",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Serbia"
    ]
  },
  {
    "name": "Moldova, Republic of",
    "exports": [
      "Argentina",
      "Austria",
      "Bangladesh",
      "Armenia",
      "Belgium",
      "Bosnia and Herzegovina",
      "Brazil",
      "Bulgaria",
      "Belarus",
      "Canada",
      "Chile",
      "China",
      "Chinese Taipei",
      "Costa Rica",
      "Croatia",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "Estonia",
      "Finland",
      "France",
      "Georgia",
      "Germany",
      "Greece",
      "Hong Kong, China",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Ireland",
      "Israel",
      "Italy",
      "Japan",
      "Jordan",
      "Korea, Republic of",
      "Latvia",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Malta",
      "Mexico",
      "Netherlands",
      "Norway",
      "Pakistan",
      "Poland",
      "Portugal",
      "Romania",
      "Russian Federation",
      "Singapore",
      "Slovak Republic",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "Sweden",
      "Switzerland",
      "Thailand",
      "Turkey",
      "Ukraine",
      "North Macedonia",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Serbia",
      "Montenegro"
    ]
  },
  {
    "name": "Morocco",
    "exports": [
      "Algeria",
      "Angola",
      "Argentina",
      "Australia",
      "Austria",
      "Belgium",
      "Brazil",
      "Bulgaria",
      "Canada",
      "Chile",
      "China",
      "Chinese Taipei",
      "Croatia",
      "Cuba",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "El Salvador",
      "Ethiopia",
      "Estonia",
      "Finland",
      "France",
      "Germany",
      "Greece",
      "Hungary",
      "India",
      "Indonesia",
      "Iraq",
      "Ireland",
      "Italy",
      "Japan",
      "Jordan",
      "Korea, Republic of",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Mexico",
      "Netherlands",
      "New Zealand",
      "Norway",
      "Pakistan",
      "Poland",
      "Portugal",
      "Qatar",
      "Romania",
      "Russian Federation",
      "Saudi Arabia, Kingdom of",
      "Senegal",
      "Singapore",
      "Slovak Republic",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "Sweden",
      "Switzerland",
      "Thailand",
      "United Arab Emirates",
      "Tunisia",
      "Turkey",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Uruguay"
    ]
  },
  {
    "name": "New Zealand",
    "exports": [
      "Argentina",
      "Australia",
      "Austria",
      "Belgium",
      "Brazil",
      "Bulgaria",
      "Myanmar",
      "Belarus",
      "Cambodia",
      "Canada",
      "Sri Lanka",
      "Chile",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Croatia",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "Ecuador",
      "Estonia",
      "Fiji",
      "Finland",
      "France",
      "Georgia",
      "Germany",
      "Greece",
      "Guatemala",
      "Hong Kong, China",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran",
      "Ireland",
      "Israel",
      "Italy",
      "Japan",
      "Jordan",
      "Korea, Republic of",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Madagascar",
      "Malaysia",
      "Malta",
      "Mexico",
      "Morocco",
      "Nepal",
      "Netherlands",
      "Vanuatu",
      "Norway",
      "Pakistan",
      "Philippines",
      "Poland",
      "Portugal",
      "Romania",
      "Russian Federation",
      "Saudi Arabia, Kingdom of",
      "Sierra Leone",
      "Singapore",
      "Slovak Republic",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "Eswatini",
      "Sweden",
      "Switzerland",
      "Thailand",
      "Togo",
      "Trinidad and Tobago",
      "United Arab Emirates",
      "Tunisia",
      "Turkey",
      "Ukraine",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Samoa"
    ]
  },
  {
    "name": "Nicaragua",
    "exports": [
      "Albania",
      "Argentina",
      "Australia",
      "Austria",
      "Bangladesh",
      "Belgium",
      "Brazil",
      "Canada",
      "Chile",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Costa Rica",
      "Cuba",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "Ecuador",
      "El Salvador",
      "Finland",
      "France",
      "Germany",
      "Greece",
      "Guatemala",
      "Honduras",
      "Hong Kong, China",
      "Hungary",
      "India",
      "Indonesia",
      "Iran",
      "Ireland",
      "Israel",
      "Italy",
      "Japan",
      "Jordan",
      "Korea, Republic of",
      "Liechtenstein",
      "Malaysia",
      "Malta",
      "Mexico",
      "Netherlands",
      "New Zealand",
      "Norway",
      "Panama",
      "Paraguay",
      "Peru",
      "Poland",
      "Portugal",
      "Russian Federation",
      "Singapore",
      "Slovak Republic",
      "Viet Nam",
      "Slovenia",
      "Spain",
      "Sweden",
      "Switzerland",
      "Thailand",
      "Turkey",
      "Ukraine",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Uruguay",
      "Venezuela, Bolivarian Republic of"
    ]
  },
  {
    "name": "Norway",
    "exports": [
      "Argentina",
      "Australia",
      "Austria",
      "Belgium",
      "Brazil",
      "Belize",
      "Bulgaria",
      "Cambodia",
      "Canada",
      "Chile",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Costa Rica",
      "Croatia",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Dominica",
      "Dominican Republic",
      "Ecuador",
      "Estonia",
      "Finland",
      "France",
      "Germany",
      "Greece",
      "Honduras",
      "Hong Kong, China",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran",
      "Ireland",
      "Israel",
      "Italy",
      "Cote d'Ivoire",
      "Jamaica",
      "Japan",
      "Jordan",
      "Korea, Republic of",
      "Latvia",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Malaysia",
      "Malta",
      "Mexico",
      "Nepal",
      "Netherlands",
      "New Zealand",
      "Nigeria",
      "Pakistan",
      "Paraguay",
      "Peru",
      "Philippines",
      "Poland",
      "Portugal",
      "Romania",
      "Russian Federation",
      "Senegal",
      "Singapore",
      "Slovak Republic",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "Sweden",
      "Switzerland",
      "Syrian Arab Republic",
      "Thailand",
      "Tunisia",
      "Turkey",
      "Ukraine",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Burkina Faso",
      "Venezuela, Bolivarian Republic of",
      "Serbia"
    ]
  },
  {
    "name": "Paraguay",
    "exports": [
      "Albania",
      "Argentina",
      "Australia",
      "Austria",
      "Belgium",
      "Bolivia, Plurinational State of",
      "Brazil",
      "Canada",
      "Chile",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Costa Rica",
      "Cuba",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "Ecuador",
      "El Salvador",
      "Finland",
      "France",
      "Germany",
      "Greece",
      "Hungary",
      "India",
      "Ireland",
      "Israel",
      "Italy",
      "Japan",
      "Korea, Republic of",
      "Lithuania",
      "Malta",
      "Mexico",
      "Netherlands",
      "Norway",
      "Peru",
      "Portugal",
      "Russian Federation",
      "Singapore",
      "Slovenia",
      "South Africa",
      "Spain",
      "Sweden",
      "Switzerland",
      "Thailand",
      "Turkey",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Venezuela, Bolivarian Republic of"
    ]
  },
  {
    "name": "Peru",
    "exports": [
      "Argentina",
      "Australia",
      "Austria",
      "Bangladesh",
      "Belgium",
      "Bolivia, Plurinational State of",
      "Brazil",
      "Bulgaria",
      "Canada",
      "Chile",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Costa Rica",
      "Croatia",
      "Cuba",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "Ecuador",
      "El Salvador",
      "Finland",
      "France",
      "Germany",
      "Greece",
      "Guatemala",
      "Hong Kong, China",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran",
      "Ireland",
      "Israel",
      "Italy",
      "Japan",
      "Jordan",
      "Korea, Republic of",
      "Latvia",
      "Liechtenstein",
      "Lithuania",
      "Malaysia",
      "Mexico",
      "Nepal",
      "Netherlands",
      "New Zealand",
      "Norway",
      "Pakistan",
      "Panama",
      "Paraguay",
      "Philippines",
      "Poland",
      "Portugal",
      "Singapore",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "Sweden",
      "Switzerland",
      "Thailand",
      "Turkey",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Uruguay",
      "Venezuela, Bolivarian Republic of"
    ]
  },
  {
    "name": "Philippines",
    "exports": [
      "Argentina",
      "Australia",
      "Austria",
      "Bangladesh",
      "Belgium",
      "Brazil",
      "Bulgaria",
      "Belarus",
      "Cambodia",
      "Canada",
      "Chile",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Costa Rica",
      "Croatia",
      "Cuba",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "Finland",
      "France",
      "Germany",
      "Greece",
      "Holy See",
      "Hong Kong, China",
      "Hungary",
      "India",
      "Indonesia",
      "Iran",
      "Ireland",
      "Israel",
      "Italy",
      "Japan",
      "Jordan",
      "Kenya",
      "Korea, Republic of",
      "Latvia",
      "Liechtenstein",
      "Luxembourg",
      "Macao, China",
      "Malaysia",
      "Mexico",
      "Morocco",
      "Oman",
      "Netherlands",
      "New Zealand",
      "Norway",
      "Pakistan",
      "Peru",
      "Poland",
      "Portugal",
      "Qatar",
      "Romania",
      "Singapore",
      "Slovak Republic",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "Sweden",
      "Switzerland",
      "Thailand",
      "United Arab Emirates",
      "Turkey",
      "United Kingdom",
      "United States of America",
      "Uruguay"
    ]
  },
  {
    "name": "Qatar",
    "exports": [
      "Albania",
      "Argentina",
      "Australia",
      "Austria",
      "Bangladesh",
      "Belgium",
      "Bosnia and Herzegovina",
      "Brazil",
      "Bulgaria",
      "Canada",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Costa Rica",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "El Salvador",
      "Finland",
      "France",
      "Georgia",
      "Germany",
      "Greece",
      "Hungary",
      "India",
      "Indonesia",
      "Ireland",
      "Italy",
      "Japan",
      "Jordan",
      "Kenya",
      "Korea, Republic of",
      "Kuwait, the State of",
      "Lebanese Republic",
      "Lithuania",
      "Luxembourg",
      "Malaysia",
      "Mexico",
      "Oman",
      "Netherlands",
      "New Zealand",
      "Norway",
      "Pakistan",
      "Peru",
      "Poland",
      "Portugal",
      "Romania",
      "Saudi Arabia, Kingdom of",
      "Singapore",
      "Slovak Republic",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "Sudan",
      "Suriname",
      "Eswatini",
      "Sweden",
      "Switzerland",
      "Thailand",
      "United Arab Emirates",
      "Turkey",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Uruguay",
      "Serbia"
    ]
  },
  {
    "name": "Saudi Arabia, Kingdom of",
    "exports": [
      "Algeria",
      "Antigua and Barbuda",
      "Argentina",
      "Australia",
      "Austria",
      "Bahrain, Kingdom of",
      "Bangladesh",
      "Belgium",
      "Brazil",
      "Brunei Darussalam",
      "Bulgaria",
      "Cambodia",
      "Canada",
      "Sri Lanka",
      "Chile",
      "China",
      "Chinese Taipei",
      "Costa Rica",
      "Croatia",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Dominica",
      "Dominican Republic",
      "Estonia",
      "Finland",
      "France",
      "Georgia",
      "Germany",
      "Greece",
      "Hungary",
      "India",
      "Indonesia",
      "Iran",
      "Iraq",
      "Ireland",
      "Italy",
      "Jamaica",
      "Japan",
      "Jordan",
      "Korea, Republic of",
      "Kuwait, the State of",
      "Lebanese Republic",
      "Latvia",
      "Lithuania",
      "Malaysia",
      "Malta",
      "Mexico",
      "Morocco",
      "Oman",
      "Nepal",
      "Netherlands",
      "New Zealand",
      "Norway",
      "Pakistan",
      "Peru",
      "Philippines",
      "Poland",
      "Portugal",
      "Qatar",
      "Romania",
      "Russian Federation",
      "Singapore",
      "Slovak Republic",
      "Slovenia",
      "South Africa",
      "Spain",
      "Sudan",
      "Sweden",
      "Switzerland",
      "Syrian Arab Republic",
      "Thailand",
      "United Arab Emirates",
      "Tunisia",
      "Turkey",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Uruguay",
      "Samoa"
    ]
  },
  {
    "name": "Senegal",
    "exports": [
      "Afghanistan",
      "Albania",
      "Antigua and Barbuda",
      "Argentina",
      "Australia",
      "Austria",
      "Bangladesh",
      "Armenia",
      "Belgium",
      "Brazil",
      "Bulgaria",
      "Cambodia",
      "Canada",
      "China",
      "Denmark",
      "Dominican Republic",
      "France",
      "Georgia",
      "Germany",
      "Greece",
      "Hungary",
      "India",
      "Indonesia",
      "Iran",
      "Ireland",
      "Italy",
      "Cote d'Ivoire",
      "Korea, Republic of",
      "Kuwait, the State of",
      "Macao, China",
      "Mali",
      "Malta",
      "Mauritania",
      "Mauritius",
      "Mexico",
      "Morocco",
      "Oman",
      "Netherlands",
      "Pakistan",
      "Peru",
      "Poland",
      "Portugal",
      "Russian Federation",
      "Saudi Arabia, Kingdom of",
      "Slovenia",
      "South Africa",
      "Spain",
      "Suriname",
      "Sweden",
      "Switzerland",
      "Togo",
      "United Arab Emirates",
      "Tunisia",
      "Turkey",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Montenegro",
      "Zambia"
    ]
  },
  {
    "name": "Seychelles",
    "exports": [
      "Andorra",
      "Australia",
      "Belgium",
      "Canada",
      "Sri Lanka",
      "China",
      "Chinese Taipei",
      "Cyprus",
      "Denmark",
      "Finland",
      "France",
      "Germany",
      "Hong Kong, China",
      "Hungary",
      "India",
      "Indonesia",
      "Ireland",
      "Italy",
      "Kenya",
      "Korea, Republic of",
      "Lithuania",
      "Luxembourg",
      "Malaysia",
      "Mali",
      "Mauritius",
      "Mexico",
      "Oman",
      "Namibia",
      "Netherlands",
      "New Zealand",
      "Philippines",
      "Portugal",
      "Russian Federation",
      "Saudi Arabia, Kingdom of",
      "Singapore",
      "Viet Nam",
      "South Africa",
      "Spain",
      "Sweden",
      "Switzerland",
      "Thailand",
      "United Arab Emirates",
      "Ukraine",
      "United Kingdom",
      "United States of America",
      "Serbia"
    ]
  },
  {
    "name": "Singapore",
    "exports": [
      "Argentina",
      "Australia",
      "Austria",
      "Bahrain, Kingdom of",
      "Bangladesh",
      "Belgium",
      "Brazil",
      "Belize",
      "Brunei Darussalam",
      "Bulgaria",
      "Myanmar",
      "Belarus",
      "Cambodia",
      "Canada",
      "Sri Lanka",
      "Chile",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Costa Rica",
      "Croatia",
      "Cuba",
      "Cyprus",
      "Czech Republic",
      "Benin",
      "Denmark",
      "Dominican Republic",
      "Ecuador",
      "Estonia",
      "Finland",
      "France",
      "Georgia",
      "Germany",
      "Greece",
      "Hong Kong, China",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran",
      "Ireland",
      "Israel",
      "Italy",
      "Japan",
      "Jordan",
      "Kenya",
      "Korea, Republic of",
      "Kyrgyz Republic",
      "Lao People's Democratic Republic",
      "Latvia",
      "Liechtenstein",
      "Lithuania",
      "Macao, China",
      "Madagascar",
      "Malaysia",
      "Mali",
      "Malta",
      "Mauritius",
      "Mexico",
      "Mongolia",
      "Moldova, Republic of",
      "Namibia",
      "Nepal",
      "Netherlands",
      "New Zealand",
      "Nigeria",
      "Norway",
      "Pakistan",
      "Panama",
      "Peru",
      "Philippines",
      "Poland",
      "Portugal",
      "Timor-Leste",
      "Qatar",
      "Romania",
      "Russian Federation",
      "Saudi Arabia, Kingdom of",
      "Slovak Republic",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "South Sudan",
      "Sweden",
      "Switzerland",
      "Thailand",
      "United Arab Emirates",
      "Tunisia",
      "Turkey",
      "Ukraine",
      "North Macedonia",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Uruguay",
      "Serbia"
    ]
  },
  {
    "name": "South Africa",
    "exports": [
      "Algeria",
      "Angola",
      "Argentina",
      "Australia",
      "Austria",
      "Bangladesh",
      "Belgium",
      "Bosnia and Herzegovina",
      "Botswana",
      "Brazil",
      "Brunei Darussalam",
      "Bulgaria",
      "Cambodia",
      "Cameroon",
      "Canada",
      "Cabo Verde",
      "Chile",
      "China",
      "Chinese Taipei",
      "Democratic Republic of the Congo",
      "Croatia",
      "Cuba",
      "Cyprus",
      "Czech Republic",
      "Benin",
      "Denmark",
      "Dominica",
      "Dominican Republic",
      "Ethiopia",
      "Finland",
      "France",
      "Germany",
      "Ghana",
      "Greece",
      "Guatemala",
      "Haiti",
      "Hong Kong, China",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran",
      "Ireland",
      "Israel",
      "Italy",
      "Cote d'Ivoire",
      "Japan",
      "Kazakhstan",
      "Jordan",
      "Kenya",
      "Korea, Republic of",
      "Lesotho",
      "Latvia",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Madagascar",
      "Malawi",
      "Malaysia",
      "Malta",
      "Mauritania",
      "Mauritius",
      "Mexico",
      "Morocco",
      "Mozambique",
      "Oman",
      "Namibia",
      "Nepal",
      "Netherlands",
      "Vanuatu",
      "New Zealand",
      "Nigeria",
      "Norway",
      "Pakistan",
      "Peru",
      "Philippines",
      "Poland",
      "Portugal",
      "Romania",
      "Russian Federation",
      "Rwanda",
      "Saudi Arabia, Kingdom of",
      "Senegal",
      "Seychelles",
      "Singapore",
      "Viet Nam",
      "Slovenia",
      "Zimbabwe",
      "Spain",
      "Sudan",
      "Eswatini",
      "Sweden",
      "Switzerland",
      "Thailand",
      "United Arab Emirates",
      "Turkey",
      "Uganda",
      "Ukraine",
      "Egypt",
      "United Kingdom",
      "Tanzania",
      "United States of America",
      "Burkina Faso",
      "Uruguay",
      "Zambia"
    ]
  },
  {
    "name": "Switzerland",
    "exports": [
      "Albania",
      "Algeria",
      "Antigua and Barbuda",
      "Azerbaijan",
      "Argentina",
      "Australia",
      "Austria",
      "Bahrain, Kingdom of",
      "Bangladesh",
      "Armenia",
      "Belgium",
      "Bolivia, Plurinational State of",
      "Bosnia and Herzegovina",
      "Brazil",
      "Bulgaria",
      "Belarus",
      "Cambodia",
      "Cameroon",
      "Canada",
      "Chile",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Congo",
      "Democratic Republic of the Congo",
      "Costa Rica",
      "Croatia",
      "Cuba",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "Ecuador",
      "El Salvador",
      "Ethiopia",
      "Estonia",
      "Finland",
      "France",
      "Djibouti",
      "Georgia",
      "Germany",
      "Ghana",
      "Greece",
      "Guinea",
      "Honduras",
      "Hong Kong, China",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran",
      "Iraq",
      "Ireland",
      "Israel",
      "Italy",
      "Cote d'Ivoire",
      "Japan",
      "Kazakhstan",
      "Jordan",
      "Kenya",
      "Korea, Republic of",
      "Kuwait, the State of",
      "Kyrgyz Republic",
      "Lebanese Republic",
      "Latvia",
      "Lithuania",
      "Luxembourg",
      "Madagascar",
      "Malaysia",
      "Malta",
      "Mauritius",
      "Mexico",
      "Moldova, Republic of",
      "Morocco",
      "Oman",
      "Nepal",
      "Netherlands",
      "New Zealand",
      "Nicaragua",
      "Niger",
      "Nigeria",
      "Norway",
      "Pakistan",
      "Panama",
      "Paraguay",
      "Peru",
      "Philippines",
      "Poland",
      "Portugal",
      "Qatar",
      "Romania",
      "Russian Federation",
      "Saudi Arabia, Kingdom of",
      "Senegal",
      "Singapore",
      "Slovak Republic",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Zimbabwe",
      "Spain",
      "Eswatini",
      "Sweden",
      "Thailand",
      "Togo",
      "Trinidad and Tobago",
      "United Arab Emirates",
      "Tunisia",
      "Turkey",
      "Ukraine",
      "Egypt",
      "United Kingdom",
      "Tanzania",
      "United States of America",
      "Burkina Faso",
      "Uruguay",
      "Venezuela, Bolivarian Republic of",
      "Samoa",
      "Serbia",
      "Montenegro",
      "Zambia"
    ]
  },
  {
    "name": "Thailand",
    "exports": [
      "Argentina",
      "Australia",
      "Austria",
      "Bahrain, Kingdom of",
      "Bangladesh",
      "Belgium",
      "Bhutan",
      "Brazil",
      "Bulgaria",
      "Myanmar",
      "Cambodia",
      "Canada",
      "Sri Lanka",
      "Chile",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Costa Rica",
      "Croatia",
      "Cuba",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "Estonia",
      "Finland",
      "France",
      "Georgia",
      "Germany",
      "Greece",
      "Hong Kong, China",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran",
      "Ireland",
      "Israel",
      "Italy",
      "Japan",
      "Jordan",
      "Korea, Republic of",
      "Lao People's Democratic Republic",
      "Latvia",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Malaysia",
      "Mexico",
      "Oman",
      "Netherlands",
      "New Zealand",
      "Nicaragua",
      "Nigeria",
      "Norway",
      "Pakistan",
      "Philippines",
      "Poland",
      "Portugal",
      "Romania",
      "Russian Federation",
      "Singapore",
      "Slovak Republic",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "Eswatini",
      "Sweden",
      "Switzerland",
      "United Arab Emirates",
      "Turkey",
      "Ukraine",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Serbia"
    ]
  },
  {
    "name": "Togo",
    "exports": [
      "Argentina",
      "Austria",
      "Bangladesh",
      "Belgium",
      "Botswana",
      "Brazil",
      "Cambodia",
      "China",
      "Cuba",
      "Benin",
      "Denmark",
      "Ethiopia",
      "France",
      "Germany",
      "Ghana",
      "Hungary",
      "India",
      "Israel",
      "Italy",
      "Cote d'Ivoire",
      "Japan",
      "Jordan",
      "Korea, Republic of",
      "Lebanese Republic",
      "Mali",
      "Mauritius",
      "Morocco",
      "Netherlands",
      "Niger",
      "Poland",
      "Portugal",
      "Senegal",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "Eswatini",
      "Switzerland",
      "United Arab Emirates",
      "Tunisia",
      "Turkey",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Burkina Faso"
    ]
  },
  {
    "name": "Ukraine",
    "exports": [
      "Argentina",
      "Australia",
      "Austria",
      "Armenia",
      "Belgium",
      "Bolivia, Plurinational State of",
      "Bosnia and Herzegovina",
      "Brazil",
      "Bulgaria",
      "Belarus",
      "Canada",
      "Sri Lanka",
      "Chile",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Costa Rica",
      "Croatia",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "Estonia",
      "Finland",
      "France",
      "Georgia",
      "Germany",
      "Greece",
      "Hong Kong, China",
      "Hungary",
      "India",
      "Indonesia",
      "Iran",
      "Ireland",
      "Israel",
      "Italy",
      "Japan",
      "Kazakhstan",
      "Jordan",
      "Korea, Republic of",
      "Kyrgyz Republic",
      "Latvia",
      "Lithuania",
      "Malaysia",
      "Malta",
      "Mexico",
      "Moldova, Republic of",
      "Morocco",
      "Oman",
      "Netherlands",
      "New Zealand",
      "Norway",
      "Pakistan",
      "Peru",
      "Poland",
      "Portugal",
      "Romania",
      "Russian Federation",
      "Saudi Arabia, Kingdom of",
      "Singapore",
      "Slovak Republic",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "Sweden",
      "Switzerland",
      "Syrian Arab Republic",
      "Tajikistan",
      "Thailand",
      "Turkey",
      "North Macedonia",
      "Egypt",
      "United Kingdom",
      "United States of America",
      "Uruguay",
      "Uzbekistan",
      "Serbia",
      "Montenegro"
    ]
  },
  {
    "name": "United States of America",
    "exports": [
      "Azerbaijan",
      "Argentina",
      "Australia",
      "Austria",
      "Bahamas",
      "Bangladesh",
      "Belgium",
      "Brazil",
      "Bulgaria",
      "Cameroon",
      "Canada",
      "Chile",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Democratic Republic of the Congo",
      "Costa Rica",
      "Croatia",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "El Salvador",
      "Estonia",
      "Finland",
      "France",
      "Djibouti",
      "Gabon",
      "Georgia",
      "Germany",
      "Ghana",
      "Greece",
      "Grenada",
      "Guatemala",
      "Honduras",
      "Hong Kong, China",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Ireland",
      "Israel",
      "Italy",
      "Cote d'Ivoire",
      "Japan",
      "Jordan",
      "Kenya",
      "Korea, Republic of",
      "Latvia",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Macao, China",
      "Malaysia",
      "Mali",
      "Malta",
      "Mauritania",
      "Mauritius",
      "Mexico",
      "Morocco",
      "Oman",
      "Namibia",
      "Nepal",
      "Netherlands",
      "New Zealand",
      "Nicaragua",
      "Nigeria",
      "Norway",
      "Pakistan",
      "Panama",
      "Paraguay",
      "Peru",
      "Philippines",
      "Poland",
      "Portugal",
      "Romania",
      "Russian Federation",
      "Saudi Arabia, Kingdom of",
      "Senegal",
      "Singapore",
      "Slovak Republic",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "Eswatini",
      "Sweden",
      "Switzerland",
      "Thailand",
      "Trinidad and Tobago",
      "United Arab Emirates",
      "Turkey",
      "Ukraine",
      "Egypt",
      "United Kingdom",
      "Uruguay"
    ]
  },
  {
    "name": "Uruguay",
    "exports": [
      "Argentina",
      "Australia",
      "Austria",
      "Belgium",
      "Brazil",
      "Canada",
      "Chile",
      "China",
      "Chinese Taipei",
      "Colombia",
      "Croatia",
      "Cuba",
      "Czech Republic",
      "Denmark",
      "Dominican Republic",
      "Ecuador",
      "Finland",
      "France",
      "Germany",
      "Hong Kong, China",
      "Hungary",
      "India",
      "Indonesia",
      "Ireland",
      "Israel",
      "Italy",
      "Japan",
      "Korea, Republic of",
      "Latvia",
      "Lithuania",
      "Mexico",
      "Morocco",
      "Netherlands",
      "New Zealand",
      "Norway",
      "Panama",
      "Paraguay",
      "Peru",
      "Poland",
      "Portugal",
      "Romania",
      "Russian Federation",
      "Singapore",
      "South Africa",
      "Spain",
      "Sweden",
      "Switzerland",
      "Thailand",
      "Turkey",
      "Egypt",
      "United Kingdom",
      "United States of America"
    ]
  },
  {
    "name": "Montenegro",
    "exports": [
      "Australia",
      "Austria",
      "Belgium",
      "Bosnia and Herzegovina",
      "Brazil",
      "Bulgaria",
      "Canada",
      "China",
      "Croatia",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Dominica",
      "Finland",
      "France",
      "Germany",
      "Greece",
      "Hungary",
      "India",
      "Indonesia",
      "Ireland",
      "Israel",
      "Italy",
      "Japan",
      "Korea, Republic of",
      "Lithuania",
      "Malta",
      "Mexico",
      "Netherlands",
      "Pakistan",
      "Poland",
      "Portugal",
      "Romania",
      "Russian Federation",
      "Slovak Republic",
      "Viet Nam",
      "Slovenia",
      "South Africa",
      "Spain",
      "Sweden",
      "Switzerland",
      "Thailand",
      "Turkey",
      "Ukraine",
      "North Macedonia",
      "United Kingdom",
      "United States of America",
      "Serbia"
    ]
  }
]